# Generated by Django 5.1.6 on 2025-06-14 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioHuella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('huella_id', models.IntegerField(blank=True, help_text='ID único de la huella asociada al usuario', null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del registro de entrada')),
                ('usuario', models.ForeignKey(help_text='Usuario asociado a este registro de entrada', on_delete=django.db.models.deletion.CASCADE, related_name='registros_entrada', to='app_seguridad_acceso_biometrico.usuariohuella')),
            ],
        ),
    ]
