# Generated by Django 5.1.6 on 2025-06-27 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguridad_acceso_biometrico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroentrada',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario asociado a este registro de entrada', on_delete=django.db.models.deletion.CASCADE, related_name='registros_entrada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroentrada',
            name='metodo',
            field=models.CharField(default='desconocido', max_length=20),
        ),
        migrations.DeleteModel(
            name='UsuarioHuella',
        ),
    ]
