# Generated by Django 5.1.6 on 2025-07-02 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguridad_acceso_biometrico', '0003_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
    ]
